apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: default
  labels:
    app: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      name: prometheus-server
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus-server
          image: prom/prometheus
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.route-prefix=/prometheus
            - --web.external-url=https://www.myexample.com.tw/prometheus


          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
              readOnly: true



      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
            items:
              - key: prometheus.yaml
                path: prometheus.yml
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: default
spec:
  selector:
    app: prometheus-server #選擇的 app=prometheus-server 標籤的 Pod
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: http
  type: NodePort